### ISSUE TITLE
[SORTEIO] Manter registro de histório do sorteio

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#100]
## **Contexto**

- O Mapas Culturais terá a possibilidade de gerar um sorteio de alguns inscritos habilitados e ranquear o resultado, mas a plataforma deve guardar esse registro para eventual dúvida que surgir no tocante a integridade do sorteio,

## **Objetivo**

**Como** sou uma pessoa desenvolvedora
**Quero** guardar os dados do sorteio no banco
**Para** sempre que precisar extrair algum informação quando for necessário

## **Validação**

- [x] Guardar quem gerou o sorteio (usuário logado)
- [x] Guardar data e hora de cada nome sorteado
- [x] Guardar o relacionamento do sorteio com a oportunidade
- [x] Guardar o relacionamento do sorteio com a inscrição
- [x] Guardar de qual categoria foi sorteada com o numero da inscrição

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Guardar informação do sorteio  
**Dado que** sou uma pessoa desenvolvedora do mapas culturais
**Quando** ocorrer o evento do sorteio
**Então** guardo cada informação necessária no banco de dados

# Observações

**Comment by jgaguiarm** [comment]
Realizado teste da funcionalidade de sorteio e validada a persistência dos dados no banco de dados.
