### ISSUE TITLE
[SORTEIO] Gerar arquivo .xls do sorteio

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#103]
## **Contexto**

- O Mapas Culturais tem que ter a opção mostrar os sorteados através de um ranking em formato .xlsx

## **Objetivo**

**Como** sou uma pessoa desenvolvedora
**Quero** disponibilizar um botão
**Para** o gestor da oportunidade clicar para gerar um arquivo em XLSX.

## **Escopo**

- [x] Criar endpoint para baixar arquivo
- [x] Integrar botão ao backend

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Baixar planilha com a lista sorteada
**Dado que** sou adiministrador da oportunidade
**E** já ocorreu algum sorteio
**Quando** clico no botão "Baixar planilha"
**Então** um arquivo XLSX com a lista de categorias que estão listadas na tela será baixado

# Observações

**Comment by jgaguiarm** [comment]
Realizados testes no ambiente de desenvolvimento e validados os critérios de aceitação.
