### ISSUE TITLE
[CON.PUBLICA] CRUD para consulta pública

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#104]
## **Contexto**

- O Mapas Culturais deve ter a possiblidade de cadastrar informações com um link do Google Docs para documentos dispostos para uma consulta pública civil

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** criar um CRUD
**Para** o gestor da SECULT realizar operações de itens de consulta pública

## **Escopo**

- [x] Dados do Formulário (Título, Subtitulo, Link)
- [x] [Secretaria da Cultura do Estado do Ceará - SECULTCE](https://mapacultural.secult.ce.gov.br/selo/2/)

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Criar cadastro  
**Dado que** sou uma pessoa com selo SecultCe
**Quando** acessar o menu CONSULTA PUBLICA
**Então** terei uma página com um formulário para cadastro das informações

- [x] Editar item do cadastro
**Dado que** sou uma pessoa com selo SecultCe
**Quando** acessar o menu CONSULTA PUBLICA
**Então** terei uma página com uma listagem de itens cadastrado que posso editar a informação do item

- [x] Pesquisar item do cadastro
**Dado que** sou uma pessoa com selo SecultCe
**Quando** acessar o menu CONSULTA PUBLICA
**Então** terei um campo de pesquisa que posso digitar e terei um filtro com itens relacionado ao que foi digitado

- [x] Remoção item do cadastro
**Dado que** sou uma pessoa com selo SecultCe
**Quando** acessar o menu CONSULTA PUBLICA
**Então** terei uma página com uma listagem de itens cadastrado que posso remover o item da listagem

# ⚠️ Validação ⚠️

- [x] Todos os campos são obrigatórios;
- [x] Ao remover o item da listagem o mesmo não se exclui da tabela no banco de dados;

# Observações

**Comment by Yasminemaciel02** [comment]
Todos os critérios foram atendidos e funcionam perfeitamente.
A consulta pública aceita qualquer link, mesmo não sendo Google Docs. Verificar se será desta forma.

![Image](https://github.com/user-attachments/assets/009e4219-febf-48c8-9fd7-a8a65e2108d9)
