### ISSUE TITLE
Remover o envio de e-mail para todos os administradores da plataforma do mapas

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#120]
## **Contexto**

- Atualmente no Mapa Cultural quando é enviado uma mensagem de contato para o dono de uma entidade, o sistema envia um e-mail para todos os administradores da plataforma.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** enviar de disparo de e-mail 
**Para** todos os adminis da plataforma mapa cultural

## **Critérios de Aceitação**

- [ ] Enviar e-mail somente para o dono da entidade
**Dado que** sou uma pessoa que visita ou usa o mapa cultural
**Quando** eu tenho 
**Então** resulta

# Observações

![Image](https://github.com/secultce/mapasculturais-v5/assets/7341117/562cd0d1-194c-47db-9b27-d17eebf0d95d)

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

**Comment by ronnyjohnti** [comment]
De acordo com a documentação original da plataforma, usuários com as  _roles_ `saasAdmin` e `saasSuperAdmin` têm permissões de acesso ao painel de subsites e também a edição de entidades de qualquer dos subsites.
Especificamente relacionado ao e-mail, essas mesmas _roles_ também recebem todos os e-mails enviados sobre uma entidade. Enquanto perfis que contêm as roles `admin` e `superAdmin` só recebem e-mails relacionados aos seus respectivos subsites.

Definimos então que vários dos perfis que estão com as _roles_ `saasAdmin` e `saasSuperAdmin` serão reatribuídas ás `admin` e `superAdmin`, que fornecem permissões somente ao subsite do qual o estão cadastrados.
