### ISSUE TITLE
Verificar como será o parecer para o proponente quando o item não foi avaliado.

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#153]
### Contexto

- [x] Precisamos saber como fica o visual do parecer para ao proponente quando o avaliador não avalia algum item, exemplo:
Nome, CPF, e data, se por a caso o avaliador avaliou somente o Nome, como é mostrado para o proponente os outros dois itens que não foram avaliados?

- [x] Precisamos saber como fica o visual do parecer para o proponente quando tem avaliador que não realizou a avaliação, mostra o avaliador como pendente avaliar ou nã́o mostra nada?

**Comment by Yasminemaciel02** [comment]
Como não conseguimos avaliar pois o avaliador não recebe as inscrições, bem como o ADM da oportunidade, foi repassado aos Devs para que verifiquem e o teste prossiga em seguida.

**Comment by Yasminemaciel02** [comment]
![Image](https://github.com/secultce/mapasculturais-v5/assets/167997705/8bb6d4e0-cc32-4268-b6b2-f2654f00be84)

![Image](https://github.com/secultce/mapasculturais-v5/assets/167997705/07279626-b7a0-42c9-b7b7-6850d9852aaa)



O proponente só consegue visualizar o que foi avaliado, no caso o campo "Nome" foi o único avaliado e consta para o proponente, os demais não. Em relação ao avaliador 2, que não o avaliou, o proponente não vê nada a respeito.

**Comment by Yasminemaciel02** [comment]
O mesmo ocorre na inscrição invalidada onde o proponente visualiza somente o que foi avaliado.

![Image](https://github.com/secultce/mapasculturais-v5/assets/167997705/a50d2595-ac9b-4d57-950f-5e19fa69cd24)

**Comment by Junior-Shyko** [comment]
- Teste realizado com sucesso no domínio do mapa cultural do estado do Pará.
- Teste de funcionalidade não tem para ser concluído no domínio do Mapa Cultural do Ceara (REDESENHO)
