### ISSUE TITLE
Visualização de inscrição em rascunho

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#155]
Inscrições em rascunho não são vistas pelo adm sem permissão no mapa

**Comment by Yasminemaciel02** [comment]
Na v7 como adm da oportunidade sem permissão no mapa não consegui verificar nenhuma inscrição, em rascunho ou enviada.

![Image](https://github.com/secultce/mapasculturais-v5/assets/167997705/99d5b95f-a731-4dad-8752-0295244e06cf)



![Image](https://github.com/secultce/mapasculturais-v5/assets/167997705/b19fe916-f5d6-4126-9a38-fc1ca5e52d19)

**Comment by Yasminemaciel02** [comment]
![Image](https://github.com/secultce/mapasculturais-v5/assets/167997705/1084c714-465a-4be0-b1ac-6d6182668d27)

No Mapa do Pará o ADM da oportunidade consegue visualizar as inscrições em rascunho, vale deixar registrado que a relação de inscrições seja em rascunho, enviada ou com outro status só pode ser vista ao criar uma fase de avaliação.

![Image](https://github.com/secultce/mapasculturais-v5/assets/167997705/a9ac5b04-4e2a-4160-b454-831e87db7f82)

**Comment by Junior-Shyko** [comment]
- Teste realizado com sucesso no domínio do mapa cultural do estado do Pará.

- Teste de funcionalidade não tem para ser concluído no domínio do Mapa Cultural do Ceara (REDESENHO)
