### ISSUE TITLE
Testar versão 5.9.2-rc1

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#159]
## **Contexto**

- Atualmente o mapa cultural tem uma versão para testarmos

## **Objetivo**

**Como** uma pessoa testadora do sistema
**Quero** fazer testes das ultimas atualizações
**Para** validar as novas atualizações

## **Escopo**

- [ ] [Teste de funcionalidade pontuadas para treinamento](https://docs.google.com/document/d/1BSt01XI8b6C63mJdMu5hkPejCJgZMrjEhLG9nL3DA-M/edit#heading=h.wgdpnzz3lv0p)

## **Validação**

- [x] Gerar pdf do sorteio de uma oportunidade **sem** categoria
- [x] Gerar pdf do sorteio de uma oportunidade **com** categoria

## **Critérios de Aceitação**

- [x] Sorteio - Mostrar todo o fluxo  
**Dado que** sou um gestor de oportunidade
**Quando** eu usar uma oportunidade que se utiliza do sorteio com ou sem categorias
**Então** teria a certeza do correto funcionamento da oportunidade

- [x] Prestação de contas com multi diligências  
**Dado que** algo  
**Quando** faço  
**Então** resulta

- [x] Habilitação Documental - Novo tipo de avaliação
**Dado que** algo  
**Quando** faço  
**Então** resulta

- [x] Plugin Consulta Pública
**Dado que** sou um agente com o selo da secult ceara  
**Quando** eu acessar o painel, eu vejo um menu lateral com nome CONSULTA PÚBLICA
**Então** posso realizar todo um CRUD de consulta pública.

# Observações
Fluxo do sorteio: [Figma](https://www.figma.com/design/uHdiIiHWU61Gn9AjQd0qET/Prot%C3%B3tipos%2C-funcionalidades-e-plugins?node-id=1212-6008&t=w4ZUbnsot6Lo3eLu-0)
Documentos com as pautas: [Doc](https://docs.google.com/document/d/1BSt01XI8b6C63mJdMu5hkPejCJgZMrjEhLG9nL3DA-M/edit#heading=h.bks9esqdzkvu)

**Comment by Junior-Shyko** [comment]
Realizado teste com oportunidade sem categoria [OPP](https://mapaculturalhomolog.secult.ce.gov.br/oportunidade/5246/)
![Image](https://github.com/user-attachments/assets/dab84919-ea42-484f-ba6d-b4f99fc9d47e)

**Comment by Junior-Shyko** [comment]
Realizado teste de sorteio **com** categorias
![Image](https://github.com/user-attachments/assets/766d903f-b83d-4164-8ce2-2af0e63f03dc)

**Comment by Yasminemaciel02** [comment]
Fluxo de prestação de contas com multi diligências funcionando

![Image](https://github.com/user-attachments/assets/d321a161-bf3d-4f67-8652-b582e2da3819)

**Comment by Yasminemaciel02** [comment]
Edição do tado bem como salvar em rascunho funcionando, porém mesmo ao adicionar as informações Nº DO TEC e DATA , o documento baixado vem sem essas informações. Contudo o fluxo funciona.

![Image](https://github.com/user-attachments/assets/abd253fe-e4aa-401e-b628-36a059264030)
