### ISSUE TITLE
[BUG] - Notificação do Sorteio com agentes de status pendente

### ISSUE THREAD

**Issue by jgaguiarm** [secultce/mapasculturais-v5#165]
## **Contexto**
-Durante execução de testes aplicados à funcionalidade de sorteio na aplicação foi verificado que ao realizar sorteio com agentes com status pendente para a categoria escolhida, é retornada uma notificação informando "Esta categoria já foi sorteada" e nenhum resultado é visualizado na execução do sorteio. Verificado em "Sorteios realizados", é possível constatar que a categoria escolhida para sorteio não aparece entre as categorias de sorteios já realizados.

## **Passo para reprodução da falha**

- [ ] Sorteio sem agentes selecionados
**Dado que** que o administrador da oportunidade está na aba de "Sorteios" desta
**E** visualiza a área "Sorteio"
**E** seleciona uma categoria para sortear
**Quando** clica no botão "Realizar sorteio"
**Então** o administrador não visualiza na área "Sorteios realizados" uma lista de agentes selecionados
**E** visualiza um alerta informando que "Não há agentes selecionados para realizar o sorteio".

# Observações

**Comment by jgaguiarm** [comment]
![bug-report-sorteio-01](https://github.com/user-attachments/assets/b539db27-5289-4024-9c1b-c0ba9a0da114)
![burg-report-sorteio-02](https://github.com/user-attachments/assets/af615988-5f07-4b53-b50f-b8b8df330909)

**Comment by Junior-Shyko** [comment]
Problema sanado na issue https://github.com/secultce/mapasculturais-v5/issues/168
