### ISSUE TITLE
Rodapé com identidade visual da secult nos arquivos em PDF

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#167]
## **Contexto**

- Atualmente o rodapé do pdf está com o endereço mas sem a identidade visual atual da Secult e por isso se faz necessário a inclusão do rodapé com a I.V atual

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** adicionar uma imagem ao rodapé do pdf
**Para** quando houver uma impressão, ela sair com a I.V atual

## **Escopo**

- [x] Seguir o modelo do timbrado

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Novo rodapé na página  
**Dado que** uma pessoa usuária do mapa cultural
**Quando** clico em algum botão que gera um pdf
**Então** o rodapé verei o rodapé atual da I.V da secult ceara

# Observações
Timbrado: https://docs.google.com/document/d/1REgjiEvK7EfmnObQ0hBcM4zJ58PYUxN8/edit
PDF do sorteio: https://mapaculturalhomolog.secult.ce.gov.br/sorteio-inscricoes/pdf/5247/

**Comment by Yasminemaciel02** [comment]
No teste realizado não houveram problemas e a identidade visual está visível no PDF do sorteio.
