### ISSUE TITLE
[SORTEIO] Disponibilizar multi sorteios para um gestor

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#168]
## **Contexto**

- Atualmente o sorteio tem somente a possibilidade de uma única vez gerar um sorteio, mas essa ação irá se repetir por algumas vezes na mesma oportunidade;

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** disponibilizar múltiplos sorteios
**Para** quando houver necessidade de novos sorteios, isso poder acontecer

## **Escopo**

- [x] Seguir o padrão de acordo com o layout do [Figma](https://www.figma.com/design/uHdiIiHWU61Gn9AjQd0qET/Prot%C3%B3tipos%2C-funcionalidades-e-plugins?node-id=1632-6780&t=yJHDVBRMTubsUbZ0-1)

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Guardar histórico de cada sorteio  
**Dado que** sou um gestor da oportunidade  
**Quando** eu gerar um sorteio
**Então** ficará um registro de histórico da realização do sorteio

- [x] Próximo sorteio será realizado com novos inscritos
**Dado que** algo  
**Quando** faço  
**Então** resulta

## Observações
❗ Guardar os seguintes dados
    - O Agente que gerou o sorteio
    - A data e hora da publicação do sorteio
    - A quantidade de sorteados
    - Lista dos sorteados

**Comment by Yasminemaciel02** [comment]
É necessário verificar sobre o botão publicar sorteio pois o mesmo só pode ser utilizado uma única vez, o que inviabiliza o multi sorteio e a publicação e visualização do resultado pelo proponente.
