### ISSUE TITLE
[SORTEIO] Alterar a forma de visualização para os proponentes

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#169]
## **Contexto**
- Atualmente qualquer pessoa, esteja ela autenticada ou não, navegando em uma oportunidade possui acesso a aba de sorteio e a baixar a lista em planilha.

## **Objetivo**
**Como** dev
**Devo** adicionar novas validações
**Para** que somente os administradores e proponentes vejam os resultados dos sorteios
**E** que somente os administradores tenham acesso a baixar a planilha.

## **Escopo**
- [x] Adicionar validação nos botões de download XLSX
- [x] Adicionar validação para exibir aba somente aos proponentes

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**
- [x] Usuário não acessa a aba de sorteios
**Dado que** sou um usuário do Mapa Cultural
**E** não estou autencticado
**Quando** acessar uma oportunidade com sorteios publicados
**Então** não terei acesso a aba sorteios

- [x] Proponente acessa a aba de sorteios
**Dado que** sou proponente de uma oportunidade com sorteios publicados
**E** estou autenticado no Mapa Cultural
**Quando** acessar a oportunidade
**Então** terei acesso a aba sorteios

- [x] Proponente não visualiza botões de download em XLSX
**Dado que** sou proponente de uma oportunidade com sorteios publicados
**E** estou autenticado no Mapa Cultural
**Quando** acessar a oportunidade na aba de sorteios
**Então** não visualizo os botões de baixar os sorteios como XLSX

- [x] Administrador visualiza botões de download em XLSX
**Dado que** sou administrador de uma oportunidade com sorteios publicados
**E** estou autenticado no Mapa Cultural
**Quando** acessar a oportunidade na aba de sorteios
**Então** visualizo os botões de baixar os sorteios como XLSX

# Observações
Remover esses itens do frontend.
![image](https://github.com/user-attachments/assets/fbfd5ba6-d085-4dbf-8a85-4ae80b68729d)

**Comment by Yasminemaciel02** [comment]
Aprovado após teste

![Image](https://github.com/user-attachments/assets/be9a2240-337e-4528-ac1e-ffb375cc21f9)
