### ISSUE TITLE
[P.C] - Financeiro gerar relatório Final REFO

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#173]
## **Contexto**

- O financeiro enviará um relatório em pdf com o parecer do financeiro e esse será anexa a PC onde o fiscal e o proponente terá acesso ao mesmo

## **Objetivo**

**Como** dev ou ...
**Quero** realizar ...
**Para** acontecer ...

## **Escopo**

- [ Layout do Figma](https://www.figma.com/design/uHdiIiHWU61Gn9AjQd0qET/Prot%C3%B3tipos%2C-funcionalidades-e-plugins?node-id=50-1196&t=UsgAWSSikSiZj3Yd-0)

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Criar PDF para o financeiro  
**Dado que** sou um fiscal(avaliador) e posso enviar o conteúdo da diligência para o financeiro
**Quando** eu clicar em EXEC. PARCIAL ou EXEC IRREGULAR
**Então** um pdf é gerado com todo o conteúdo da diligência

# Observações

- Termos que será usado: **Aprovada, Parcialmente, Aprovada e Reprovada**
- O Fiscal irá gerar o pdf e junto com todas os arquivos enviará um email para o financeiro que irá responder ao fiscal com um relatório tendo um parecer do financeiro
- Fluxo do fomento
- ![WhatsApp Image 2024-07-16 at 14 03 23 (1)](https://github.com/user-attachments/assets/ff3723eb-750e-429e-8af8-314de6f7c75c)

**Comment by Yasminemaciel02** [comment]
Em teste foi visto a dependência da criação de uma diligência para gerar o relatório do financeiro, sendo impossível gerar sem a mesma.
