### ISSUE TITLE
[P.C] - Alterar o prazo da configuração de dias de resposta da diligência

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#176]
## **Contexto**

- Atualmente o modulo de multi diligência somente permite o prazo de resposta em dias úteis, mas se faz necessário a possibilidade de configurar para dias corridos.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** dispor de uma configuração de dias úteis e dias corridos
**Para** o gestor da oportunidade usar de acordo com a sua oportunidade

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Alterar dias de respostas
**Dado que** uma pessoa gestora de uma oportunidade
**Quando** vou escolher os dias de resposta para cada diligência
**Então** tenho a opção de escolher se será em dias úteis ou dias corridos.

# Observações

**Comment by jgaguiarm** [comment]
Realiazados testes no ambiente de desenvolvimento e validada a visualização da opões "Úteis" e "Corridos" aplicáveis ao "Tipo de dias para resposta da diligência" configurável em "Configurações de Diligência". Também foi observado que a mesma configuração se aplica para as modalidades "Diligência Simples" e "Diligência Múltipla".
![Screenshot from 2024-07-24 11-03-21](https://github.com/user-attachments/assets/74154090-5d52-4308-9d77-256f9e342b81)
