### ISSUE TITLE
Ocultar itens na página de diligências

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#189]
## **Contexto**

- Atualmente, apos gerar o TADO existe alguns itens na página que não deveriam está.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** fazer uma validação para proibir de visualizar alguns itens na página
**Para** da uma melhor experiencia ao usuário

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Remover assunto de diligência apos gerar tado
**Dado que** algo  
**Quando** faço  
**Então** resulta

- [x] Remover seleção de prestação de contas apos a geração do TADO
**Dado que** algo  
**Quando** faço  
**Então** resulta

- [x] Mostrar assunto de diligência ao clicar ABRIR DILIGÊNCIA
**Dado que** algo  
**Quando** faço  
**Então** resulta

# Observações

**Comment by Yasminemaciel02** [comment]
Aprovado após teste

**Comment by Yasminemaciel02** [comment]
Aprovado após teste, mas se faz necessário uma revisão no documento emitido para que não fique desconfigurado como o emitido abaixo.

[mpdf.pdf](https://github.com/user-attachments/files/16750543/mpdf.pdf)
