### ISSUE TITLE
Configuração de vagas para cotistas na oportunidade

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#199]
## **Contexto**
- Atualmente no mapa cultural não existe uma configuração de cotas em uma oportunidade. Sendo assim, é preciso disponibilizar nas configurações de uma oportunidade se haverá vagas para cotistas e o número de vagas.

## **Objetivo**

**Como** um administrador de uma oportunidade
**Quero** escolher se haverá vagas para cotistas
**Para** que o sistema consiga disponibilizar as vagas

## **Escopo**

- [x] Oportunidade tem que ser de avaliação técnica

## **Fora de Escopo**

Não se aplica

## **Critérios de Aceitação**

- [x] Checkbox informando se haverá vagas para cotistas
  - [x] Vir marcado por padrão
- [x] Definir número de vagas em uma oportunidade
- [x] Gravar registros de atividades

### OBSERVAÇÃO

- Pelo número de vagas da oportunidade, será retirado uma porcentagem para os cotistas (porcentagem definida por lei).

**Comment by Yasminemaciel02** [comment]
As configurações atendem aos critérios de aceitação
