### ISSUE TITLE
Correção de bug ao criar uma oportunidade

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#212]
## **Contexto**

- Ao criar uma oportunidade está acontecendo um erro e não renderiza a página.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** corrigir o erro atual da página de oportunidade em edição
**Para** o usuário poder usufruir normalmente da edição de usuário

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Corrigir bug de renderizar a página  
**Dado que** sou uma pessoa gestora da oportunidade
**Quando** acessar a página de edição de oportunidade
**Então** a página carregará normalmente para eu continuar com a edição da oportunidade

# Observações

**Comment by Yasminemaciel02** [comment]
A criação e edição está fluindo normalmente sem problemas com redenrização
