### ISSUE TITLE
Revisar documento do TADO

### ISSUE THREAD

**Issue by Yasminemaciel02** [secultce/mapasculturais-v5#216]
Se faz necessário uma revisão no documento emitido para que não fique desconfigurado como o emitido abaixo.

**Comment by Yasminemaciel02** [comment]
[mpdf.pdf](https://github.com/user-attachments/files/16750587/mpdf.pdf)

**Comment by Junior-Shyko** [comment]
Corrigido nesse [commit ](https://github.com/secultce/mapasculturais-v5/commit/2b28a7009cf536103777ae97f22a20c7dd7f218b)
