### ISSUE TITLE
[P.C] - Correções na PC

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#217]
## **Contexto**

- Atualmente a prestação de contas está com algum comportamento que não deveria acontecer. Precisa ser corrigido.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** remover o bug de renderização da página quando não tem o TADO gerado
**Para** o avaliador poder usar a página normalmente

**Como** uma pessoa desenvolvedora
**Quero** disponibilizar o assunto de diligencia apos a resposta do proponente
**Para** o avaliador poder seguir com o fluxo normalmente

**Como** uma pessoa desenvolvedora
**Quero** disponibilizar a renderização do relatório financeiro
**Para** o avaliador poder seguir com o fluxo normalmente

**Como** uma pessoa desenvolvedora
**Quero** corrigir a visualização duplicada da ultima diligência
**Para** não haver confusão de entendimento do proponente e nem do avaliador

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Não está aparecendo assunto em algumas diligências  
**Dado que** uma pessoa avaliadora  
**Quando** vou enviar uma diligência  
**Então** mostra para mim o assunto da diligência

- [x] Página de diligência não está renderizando 
**Dado que** uma pessoa avaliadora
**Quando** entro na página de diligências
**Então** a página é carregada normalmente para mim

- [x] PDF do Relatório do financeiro
**Dado que** uma pessoa avaliadora
**Quando** clico em gerar relatório para o financeiro
**Então** o PDF é gerado normalmente com o histórico das diligências

- [x] Diligências sem repetição
**Dado que** uma pessoa avaliadora
**Quando** entro na página de diligências
**Então** visualizo sem repetição o histórico das diligências

# Observações

**Comment by Yasminemaciel02** [comment]
A Prestação de contas fluindo normalmente sem bugs ou problemas
