### ISSUE TITLE
Adicionar um status da diligência.

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#22]
## **Contexto**
- Atualmente a abrir um diligência ou a mesma chegando ao fim do ciclo dela, o parecerista e nem o administrador tem a possibilidade de saber o andamento da diligencia através de um status

## **Objetivo**

**Como** dev
**Quero** mostrar uma listagem de inscrição que tenha diligência
**Para** o avaliador ter um apurado do andamento da diligência

## **Escopo**
- [x] Criar novo status para RegistrationEvaluation.
- [x] Adicionar status no frontend.
- [x] Adicionar alteração no status ao abrir diligência.
- [x] Adicionar alteração no status ao responder diligência (somente na simples).
- [x] Adicionar status ao filtro na aba de avaliações

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Adicionar uma listagem geral de inscrições em diligência
**Dado que** sou um parecerista ou gestor da oportunidade
**E** existe(m) inscrição(ões) em processo de diligência
**Quando** entro na aba de EM DILIGÊNCIA da oportunidade
**Então** consigo visualizar as inscrições que tem diligência em aberto e concluída

# Observações:
https://www.figma.com/file/uHdiIiHWU61Gn9AjQd0qET/Prot%C3%B3tipos%2C-funcionalidades-e-plugins?type=design&node-id=297-1919&mode=design&t=8IhaMplKVjZ64RLa-0

**Comment by Yasminemaciel02** [comment]
Ficou ótimo
