### ISSUE TITLE
[P.C] - Criar exclusão de diligência em rascunho

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#220]
## **Contexto**

- Atualmente na prestação de contas não tem a possibilidade de excluir o rascunho de uma diligência.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** criar a remoção de rascunho
**Para** não ter registro de sujeira nas páginas e no relatório financeiro

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Excluir rascunho em diligência
**Dado que** uma pessoa fiscal da oportunidade
**Quando** tiver uma diligência em rascunho 
**Então** eu tenho a possibilidade de clicar em EXCLUIR RASCUNHO para remover todo o conteúdo em rascunho

- [x] Não mostrar diligência em rascunho do relatório financeiro
**Dado que** uma pessoa fiscal da oportunidade
**Quando** clicar em gerar relatório financeiro
**Então** será gerado um pdf com as diligências enviada e a resposta do proponente

- [x] Desabilitar botão de editar rascunho quando o TADO for gerado
**Dado que** uma pessoa fiscal da oportunidade
**Quando** tiver uma diligência em rascunho mas o TADO está gerado
**Então** não tenho mais a possibilidade de editar o rascunho e nem de enviar a diligência

# Observações

**Comment by Yasminemaciel02** [comment]
![Image](https://github.com/user-attachments/assets/d0a0b6b0-4757-45eb-afde-2abb3e430de0)
A diligência única mostra esse erro ao ter uma diligência em rascunho excluida, o que impossibilita a criação de uma nova.
A multi diligência flui normalmente.
