### ISSUE TITLE
[P.C] Criar terminologia nas prestações de contas

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#222]
## **Contexto**

- Atualmente nas oportunidade que está configurada para multi-diligência, que são usadas para uma prestação de contas, não existe uma terminologia de prestação de contas para ficar mais claro ao fiscal e ao avaliador.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** criar um metodo
**Para** ter uma terminologia quando for utilizado a prestação de contas

## **Escopo**

- [x] Troca 'avaliador' => 'fiscal'
- [x] Troca 'avaliadores' => 'fiscais'
- [x] Troca 'avaliação' => 'monitoramento'
- [x] Troca 'avaliações' => 'monitoramentos'

## **Fora de Escopo**

- Não se aplica

## **Critérios de Aceitação**

- [x] Visualizar terminologia  na oportunidade
**Dado que** um gestor da oportunidade ou avaliador/fiscal
**E** que a oportunidade tem multi diligência
**Quando** acessar o link da oportunidade 
**E** na aba de Avaliações os termos mudarão
**Então** haverá a seguinte troca
  - O que é **AVALIAÇÃO**   =  **MONITORAMENTO**
  - o que é **AVALIAÇÕES** =  **MONITORAMENTOS**
  - O que é **AVALIADOR**  =  **FISCAL**

- [x] Visualizar terminologia  na inscrição
**Dado que** um gestor da oportunidade ou avaliador/fiscal
**E** que a oportunidade tem multi diligência
**Quando** acessar a inscrição do
**Então** haverá a seguinte troca
    - O que é **AVALIAÇÃO**    =  **MONITORAMENTO**
    - O que é **AVALIAÇÕES**  =  **MONITORAMENTOS**
    

# Observações
Documentação: https://docs.google.com/document/d/1mVKAwyDYyzvEnueBj8VnmPe5R6CMtsyurV_o1ICi9rg/edit?usp=sharing

**Comment by Yasminemaciel02** [comment]
Terminologias constando normalmente para o Fiscal e Gestor.
![Image](https://github.com/user-attachments/assets/2376c8ba-d092-4ae3-b9a9-9ff71734da9b)![Image](https://github.com/user-attachments/assets/7902b027-5d0d-4829-9e7f-a603f5525823)
