### ISSUE TITLE
[P.C] Habilitar visualização para o proponente do tado e notificar via plataforma do mapa

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#224]
## **Contexto**

- Atualmente o TADO é visualizado somente para o avaliador/fiscal, mas precisa ser disponível a visualização para o proponente

## **Objetivo**

**Como** dev ou ...
**Quero** realizar ...
**Para** acontecer ...

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Visualizar TADO  
**Dado que** sou uma pessoa proponente da oportunidade
**Quando** acessar o menu minhas prestações de contas
**Então** verei um botão de VISUALIZAR TADO se o documento for geado

- [x] Notificar proponente quando tado for gerado 
**Dado que** sou uma pessoa proponente da oportunidade
**Quando** o fiscal gerar o TADO
**Então** serei notificado via plataforma dessa ação realizada pelo fiscal
# Observações

**Comment by Junior-Shyko** [comment]
Criar novo e-mail na api de e-mail para a notificação

**Comment by Yasminemaciel02** [comment]
Critérios de aceitação funcionando após teste
![Image](https://github.com/user-attachments/assets/ba25d332-61ef-4e0d-8367-48f42acae789)
