### ISSUE TITLE
🐞 - Bug ao acessar a oportunidade

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#230]
## **Contexto**

- Na versão atual, ao entrar na página na oportunidade sem está logado a página não renderiza

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** realizar uma validação na página da oportunidade
**Para** evitar de ter erros

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Carregar toda a página
**Dado que** sou uma pessoa visitante da plataforma
**Quando** acesso a página da oportunidade
**Então** a mesma é carregada sem nenhum erro.

# Observações

**Comment by Yasminemaciel02** [comment]
Em teste o fluxo está funcionando nomalmente
