### ISSUE TITLE
🐞 - Erro ao tentar enviar diligência única

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#232]
## **Contexto**

- Atualmente no mapa quando vai tentar enviar uma diligência sendo diligência única, está dando um erro, por que está esperando um assunto

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** corrigir um erro ao enviar uma diligência
**Para** o avaliador poder enviar uma diligência

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Enviar Diligência
**Dado que** sou uma pessoa  que avalia uma inscrição  
**Quando** eu digitar a diligência e clicar em SALVAR ou ENVIAR DILIGÊNCIA
**Então** a plataforma cria um rascunho ou enviará minha diligência

# Observações
![image](https://github.com/user-attachments/assets/bb94ffb6-27ba-4daa-a75e-f65831627400)

**Comment by Yasminemaciel02** [comment]
Ao testar salvar a minha diligência em uma oportunidade técnica de diligência única em homolog, o mapa solicita que escolha um assunto, porém não existe assunto para selecionar.

![Image](https://github.com/user-attachments/assets/2df9c286-03a7-4a87-ae0e-f7c4007df70f)
