### ISSUE TITLE
[P.C] - Não está enviando diligência com assunto RELATÓRIO FINANCEIRO

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#240]
## **Contexto**

- Atualmente, quando uma pessoa avaliadora/fiscal vai tentar enviar um diligência com assunto relatório financeiro marcado, está dando uma mensagem de erro

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** refatorar o codigo
**Para** dispor a uma pessoa avaliadora enviar a diligência a um proponente.

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Enviar Diligência  
**Dado que** algo  
**Quando** faço  
**Então** resulta

# Observações

**Comment by Yasminemaciel02** [comment]
Diligência funcionando normalmente com assunto constando no documento.
