### ISSUE TITLE
[P.C] - Não está enviando notificação para o fiscal na prestação de contas.

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#337]
## **Contexto**

- Foi constatado em um treinamento que as notificações da plataforma para um fiscal apos a diligência ser respondida, não está mostrando ao fiscal responsável pela prestação de conta.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** adicionar notificações aos fiscais após uma resposta do proponente
**Para** o fiscal acompanhar as respostas das prestações de contas

## **Escopo**

- [ ] Notificação

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Notificar Fiscal
**Dado que** sou uma pessoa fiscalizadora da prestação de contas  
**Quando** o proponente responder uma mensagem da prestação de contas
**Então** eu serei notificado via plataforma do mapa cultural

# Observações

**Comment by Yasminemaciel02** [comment]
Notificações sendo enviadas para proponente e fiscal.
