### ISSUE TITLE
[P.C] “Botão abrir diligência não redireciona para aba”

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#339]
## **Contexto**

- Quando o fiscal vai clicar no botão de ABRIR A DILIGÊNCIA, então o mesmo fica na aba de FICHA, mas o comportamento é ficar ativo na aba de diligência como um proponente enviar um arquivo.

## **Objetivo**

**Como** uma pessoa 
**Quero** realizar ...
**Para** acontecer ...

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Redirecionar aba ao abrir diligência
**Dado que** sou um gestor da oportunidade
**Quando** clico em abrir uma diligência
**Então** a aba de diligência fica ativa e posso gerar a diligência

- [x] Redirecionar aba corretamente
**Dado que** sou um proponente com uma inscrição
**Quando** estou em prestação de contas e anexo um arquivo
**Então** a página é carregada e fica na aba de **DILIGÊNCIA**

# Observações

**Comment by Yasminemaciel02** [comment]
Botão direcionando para a aba
