### ISSUE TITLE
[P.C] - Criar novo status para anexar arquivos

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#340]
## **Contexto**

- Devemos criar um status "Em análise" para permitir que a pessoa fiscal possa inserir documentos ou gerar documentos de acordo com as diligências.

## **Objetivo**

**Como** dev ou ...
**Quero** realizar ...
**Para** acontecer ...

## **Escopo**

- [x] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** algo  
**Quando** faço  
**Então** resulta

# Observações

**Comment by Yasminemaciel02** [comment]
Status criado e anexando arquivos em analise, verificar sobre o nome relatório financeiro.
