### ISSUE TITLE
Retirar o projeto autorizado

### ISSUE THREAD

**Issue by Yasminemaciel02** [secultce/mapasculturais-v5#35]
## **Contexto**

- Remover a opção "O projeto está autorizado ou não" quando acessado por parecerista
![de9378e2-f7f2-4efc-986c-4786dd8479d0](https://github.com/secultce/mapasculturais-v5/assets/167997705/8f33b8f0-f317-459b-b4e2-8a1eb3f36262)

## **Objetivo**

**Como** dev
**Quero** remover a validação de mostrar a seleção de projeto aprovado
**Para** deixar disponivel o tempo todo para poder alterar a autorização do projeto

## **Escopo**

- [x] Layout do figma

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Selecionar autorização do projeto   
**Dado que** sou um parecerista  
**Quando** vou avaliar um proponente com a diligencia
**Então** a qualquer momento posso autorizar ou não o projeto do proponente

# Observações

**Comment by Yasminemaciel02** [comment]
Retirar o valor do projeto colocar só depois de projeto autorizado sem precisar de diligência

**Comment by Junior-Shyko** [comment]
Testado com a @Yasminemaciel02
