### ISSUE TITLE
Botão diligência não funciona 

### ISSUE THREAD

**Issue by Yasminemaciel02** [secultce/mapasculturais-v5#36]
## **Contexto**

- Botão de diligência não estava funcionando, verificar a necessidade de removê-lo
![8807d10f-058c-4f7c-ae54-b4da49285d62](https://github.com/secultce/mapasculturais-v5/assets/167997705/5db51569-7fef-40c6-a3dd-f4fce7d5033e)

.

## **Objetivo**

**Como** dev ou ...
**Quero** realizar ...
**Para** acontecer ...

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**Então** resulta

# Observações

**Comment by Junior-Shyko** [comment]
Ocorreu esse bug, mas por uma falha de deploy, em um ambiente com todos os assets funciona muito bem.
