### ISSUE TITLE
Criar configuração de quantidade de diligências

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#49]
## **Contexto**

- Como a diligência poderá ter apenas uma interação, então deve haver uma configuração para fazer essa definição.

## **Objetivo**

**Como** dev
**Quero** gerar uma configuração de interação
**Para** haver o entendimento de diligência única ou multi diligência

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Configurar interação de diligência  
**Dado que** sou um administrador ou avaliador da oportunidade
**Quando** eu estiver na aba de configuração de avaliação
**Então** configuro com terá diligência e se será de única interação ou multi interação

- [ ] Ocultando a opção de autorizar projeto  
**Dado que** sou um administrador ou avaliador da oportunidade
**Quando** eu estiver na aba de configuração de avaliação
**Então** então o campo de autorizar projeto somente aparecerá quando for diligência única.

# Observações

**Comment by jeff-doliveira1** [comment]
Resolvido no PR https://github.com/secultce/mapasculturais-v5/pull/78
