### ISSUE TITLE
Adicionar assunto na diligências

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#55]
## **Contexto**

- Com a possibilidade de categorizar a diligência de prestação de contas, então os diligências devem ser ordenados por categorias

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** alterar o layout da página
**Para** mostrar as diligências por grupo de categoria

## **Escopo**

- [x] Imagem do Layout

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Adicionar assunto da diligência  
**Dado que** sou uma pessoa avaliadora
**Quando** vou fazer uma diligência
**Então** de forma obrigatório eu escolho o tipo que será a minha diligência

- [x] Deixar opção marcada apos reload da página
**Dado que** sou uma pessoa avaliadora
**Quando** salvo o rascunho e recarrego a página
**Então** fica marcado o checkbox que eu confirmei

- [x] Visualizar o assunto da diligência
**Dado que** sou uma pessoa avaliadora ou proponente da diligência
**Quando** eu visualizo a diligência
**Então** é mostrado para mim qual assunto ou quais os assuntos da diligência

- [x] Adicionar Assunto na lista de diligencia
**Dado que** sou uma pessoa gestora da diligência
**Quando** na aba em diligência
**Então** posso filtrar a diligência por assunto

# Observações
![image](https://github.com/secultce/mapasculturais-v5/assets/7341117/f96d3a24-b341-4b01-8e3c-103bdf123475)

https://www.figma.com/design/uHdiIiHWU61Gn9AjQd0qET/Prot%C3%B3tipos%2C-funcionalidades-e-plugins?node-id=689-4662&t=YFesWefeEgFlJCMS-0

**Comment by Yasminemaciel02** [comment]
Na multidiligência foi possível marcar a qual assunto a mesma era relacionada.
