### ISSUE TITLE
Multi Diligencia somente na avaliação documental

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#59]
## **Contexto**
- A prestação de conta (Multi Diligencia) deve ser somente em um avaliação do tipo documental.

## **Objetivo**
**Como** uma pessoa desenvolvedora
**Quero** desenvolver uma configuração
**Para** que a multi diligencia aconteça somente na avaliação documental

## **Escopo**
- [x] Criar metadado para salvar configuração de aceitar múltiplas diligências.

## **Fora de Escopo**
- fora_de_escopo

## **Critérios de Aceitação**
- [x] Somente pode configurar uma oportunidade para ter múltiplas diligências se dor documental
**Dado que** sou um usuário administrador de uma oportunidade
**E** somente se essa oportunidade for documental
**Quando** estou na aba de edição para configurar diligência
**Então** eu terei a opção de configurar para receber múltiplas diligências.

- [x] Não pode configurar uma oportunidade para ter múltiplas diligências se não for documental
**Dado que** sou um usuário administrador de uma oportunidade
**E** essa oportunidade não for documental
**Quando** estou na aba de edição para configurar diligência
**Então** eu não terei a opção de configurar para receber múltiplas diligências.

# Observações

**Comment by Yasminemaciel02** [comment]
Teste feito confirma que diligência múltipla consta somente na avaliação documenta.

**Comment by jgaguiarm** [comment]
Realizados testes no ambiente de desenvolvimento e verificado que os critérios de aceitação foram atendidos.
