### ISSUE TITLE
Criar Release v5.9.0

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#61]
## **Contexto**

- Atualmente a versão develop juntos com algumas outras branches de features novas, então com várias funcionalidade que deve ser mergiada para uma única branch e criar uma release

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** gerar uma mesclagem das ultimas branches
**Para** atualizar a develop e a main para criar uma release

## **Escopo**
- [x] Versionamento Semântico

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Criar realease  
**Dado que** sou uma pessoa contribuidora ou desenvolvedor  
**Quando** eu acessar a página inicial do repositório
**Então** consigo saber qual é a ultima release e suas alterações pelo Changelog

# Observações

**Comment by ronnyjohnti** [comment]
Novas tasks que acredito que devem estar dentro do escopo:

## Escopo
- [ ] Adicionar log de alterações seguindo o padrão Keep A Changelog
- [ ] Atualizar referência aos commits dos plugins

**Comment by Junior-Shyko** [comment]
> Novas tasks que acredito que devem estar dentro do escopo:
> 
> ## Escopo
> * [ ]  Adicionar log de alterações seguindo o padrão Keep A Changelog
> * [ ]  Atualizar referência aos commits dos plugins

Sim, possivelmente, mas ainda iremos confirmar sobre esses pontos. Irei confirmar junto com um documento criado para padronizar todo os nossos processos de desenvolvimento.
