### ISSUE TITLE
Corrigir o subtitulo da configuração da Diligência

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#65]
## **Contexto**

- Atualmente quando cria-se uma oportunidade e na aba da **configuração da avaliação** o sub titulo da configuração de dias da diligência está sem concordância verbal e precisa ser melhorado.

## **Objetivo**

**Como** uma pessoa desenvolvedora
**Quero** ajustar o texto do sub titulo da diligência
**Para** melhorar a compreensão do admins.

**Como** uma pessoa desenvolvedora
**Quero** ajustar o texto da notificação de prazo para resposta da diligência
**Para** melhorar a compreensão do avaliador.

## **Escopo**
- [x] Remover a palavra **APENAS** do texto de notificação de prazo ao proponente

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Correção do subtítulo 
**Dado que** sou uma pessoa admin da oportunidade ou dona da oportunidade ou admin da plataforma
**Quando** eu acessar a aba da configuração da avaliação
**Então** quero visualizar uma melhor compreensão do subtitulo dos dias úteis.

- [x] Correção do texto da notificação do prazo ao proponente
**Dado que** sou uma pessoa avaliadora ou dona da oportunidade
**Quando** eu acessar a aba da diligência que esteja enviada
**Então** quero visualizar uma melhor compreensão do texto da notificação do prazo ao proponente

# Observações

**Comment by jeff-doliveira1** [comment]
Resolvido no PR https://github.com/secultce/mapasculturais-v5/pull/68
