### ISSUE TITLE
Remoção da notificação de prazo para resposta após a diligência enviada

### ISSUE THREAD

**Issue by Yasminemaciel02** [secultce/mapasculturais-v5#67]
## **Contexto**

- Após o envio da diligência, o prazo de resposta não deve mais aparecer para o proponente

## **Objetivo**

**Como** dev  devo remover a notificação de prazo após envio de diligência
**Quero**  que quando o proponente envie sua resposta a diligência, não visualize novamente a notificação
**Para** que não ocorra dificuldade de entendimento

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Remover  notificação de prazo de resposta após envio
**Dado que** sou proponente  
**Quando** faço o envio da resposta da diligência  
**Então** visualizo somente a confirmação de envio, com data e hora, sem o prazo antes mencionado

# Observações

**Comment by jeff-doliveira1** [comment]
Feito na issue https://github.com/secultce/mapasculturais-v5/issues/53
