### ISSUE TITLE
Opções de configuração da diligência

### ISSUE THREAD

**Issue by ronnyjohnti** [secultce/mapasculturais-v5#77]
## **Contexto**
- É necessário dar opção ao usuário de configurar o uso da diligência para cada oportunidade.

## **Objetivo**
**Como** desenvolvedor
**Quero** adicionar campos
**Para** o administrador da oportunidade configurar uso da diligência

## **Escopo**
- [x] Adicionar campo "Usa Diligência" com opções "Não", "Diligência Simples" e "Diligência Múltipla".
- [x] Adicionar validações da opção configurada para diligência

## **Fora de Escopo**
- Não se aplica

## **Critérios de Aceitação**

- [x] Usuário tem opção de configurar uso da diligência
**Dado que** o usuário é administrador da oportunidade
**Quando** está editando na aba de configuração da avaliação
**Então** tem acesso a opção de configurar uso da diligência.

- [x] Não é possível abrir diligência se a configuração está como "Não"
**Dado** que o usuário é um avalidor
**E** a oportunidade tem "Usa Diligência" configurado como "Não"
**Quando** acessa a ficha de inscrição
**Então** não tem acesso a abertura de diligência

- [x] Não é possível abrir mais de uma diligência se a configuração está como "Diligência Simples"
**Dado** que o usuário é um avalidor
**E** a oportunidade tem "Usa Diligência" configurado como "Diligência Simples"
**Quando** acessa uma ficha de inscrição
**E** já existe uma diligência aberta
**Então** não tem acesso a abertura de diligência

# Observações

**Comment by jgaguiarm** [comment]
Realizados testes no ambiente de desenvolvimento e verificado que todos os critérios de aceitação foram cumpridos.
