### ISSUE TITLE
Remover mensagem de aguardando resposta do proponente

### ISSUE THREAD

**Issue by Yasminemaciel02** [secultce/mapasculturais-v5#79]
## **Contexto**

- Adm, dono da oportunidade, avaliador/parecerista devem ver a mensagem da resposta do proponente somente após o envio da diligência.

## **Objetivo**

**Como** dev 
**Quero** remover a mensagem AGUARDANDO RESPOSTA do proponente
**Para** o avaliador visualizar somente quando tiver uma resposta

## **Escopo**

- [ ] Seguir imagem

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] Informação de aguardando resposta
**Dado que** sou dono,adm ou parceirista de uma oportunidade 
**Quando** consulto uma diligência enviada
**Então** tenho a informação de aguardando resposta do proponente, caso este não tenha respondido

# Observações
![image](https://github.com/secultce/mapasculturais-v5/assets/7341117/c8198014-4ad7-4d51-874a-f0e313a4bd87)

Figma: https://www.figma.com/design/uHdiIiHWU61Gn9AjQd0qET/Prot%C3%B3tipos%2C-funcionalidades-e-plugins?node-id=689-4816&t=KSzHgfnhsHAZfDii-0

**Comment by jeff-doliveira1** [comment]
Feito na issue https://github.com/secultce/mapasculturais-v5/issues/53
