### ISSUE TITLE
[SORTEIO] Criar aba de sorteio para o gestor da Op.

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#98]
## **Contexto**

- O Mapas Culturais deve ter uma aba chamada sorteio

## **Objetivo**

**Como** pessoa desenvolvedora
**Quero** adicionar uma aba a mais na visualização da oportunidade
**Para** o gestor poder ter o cenário de trabalho que ele usará

## **Escopo**

- [x] Criar aba de sorteio.
- [x] Deixar pronto para receber e validar configurações.

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Deixar a aba visível para gestores da oportunidade
**Dado que** sou um gestor da oportunidade
**E** a oportunidade está configurada para sorteio
**Quando** acessar a oportunidade
**Então** eu verei a aba "sorteio".

- [x] Aba oculta para não gestores da oportunidade
**Dado que** não tenho acessos de gestor à oportunidade
**E** a oportunidade está configurada para sorteio
**Quando** acessar a oportunidade
**Então** eu NÃO verei a aba "sorteio".

# Validação
- [x] Somente o(s) gestor(es) da oportunidade podem acessar essa aba
- [x] Essa aba **não** é acessada em modo de edição

# Observações

**Comment by jgaguiarm** [comment]
Realizados testes no ambiente de desenvolvimento e validados os critérios de aceitação.
