### ISSUE TITLE
[SORTEIO] Criar aba de sorteio para proponente ou visitante para visualizar o resultado do sorteio

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/mapasculturais-v5#99]
## **Contexto**

- O Mapas Culturais deve ter uma aba chamada sorteio que mostrará o resultado do sorteio de uma oportunidade

## **Objetivo**

**Como** sou uma pessoa desenvolvedora
**Quero** adicionar uma aba a mais na visualização da oportunidade
**Para** o proponente ou visitante poder visualizar o resultado do sorteio de uma oportunidade

## **Escopo**

- [x] Criar método para publicar o sorteio
- [x] Alterar o frontend para mostrar o sorteio ao proponente

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [x] Visualizar resultado do sorteio na aba SORTEIO
**Dado que** sou uma pessoa proponente ou visitante da plataforma
**E** a oportunidade contém sorteio(s) publicado(s)
**Quando** acessar a oportunidade
**Então** posso visualizar a lista dos sorteados na aba SORTEIO

# Observações

**Comment by jgaguiarm** [comment]
Realizado teste em ambiente de desenvolvimento e validado o critério de aceitação.
